#!/bin/sh
#SBATCH -J test_file # Job name
#SBATCH -N 1 # No. of nodes requested (we have 1)
#SBATCH -n 32 # No. of cores requested (we have 76)
#SBATCH -t 96:00:00 # Max wall time - job will be killed after 96 hours
#SBATCH --mem-per-cpu=2gb # 2 GB of RAM per CPU core, totaling 64 GB for 32 cores.
#SBATCH -e job.err # Redirects the standard error output (e.g., crash reports, errors) to the file job.err2
#SBATCH -o job.out # Redirects the standard output (e.g., regular printed messages) to the file job.out

srun vasp_std > out # Submitting the Job